export const mock = [
  {
    name: "Instance A",
    gpu: "Sample",
    storage: "2 TB SSD",
    network: "10 Gbps",
    egress: "1 TB",
    price_monthly: "$1,200",
    price_hourly: "$1.60",
  },
  {
    name: "Instance B",
    gpu: "Sample",
    storage: "1 TB SSD",
    network: "5 Gbps",
    egress: "500 GB",
    price_monthly: "$800",
    price_hourly: "$1.10",
  },
  {
    name: "Instance C",
    gpu: "Sample",
    storage: "3 TB HDD",
    network: "1 Gbps",
    egress: "2 TB",
    price_monthly: "$700",
    price_hourly: "$0.95",
  },
  {
    name: "Instance D",
    gpu: "Sample",
    storage: "512 GB SSD",
    network: "100 Mbps",
    egress: "Unlimited",
    price_monthly: "$400",
    price_hourly: "$0.50",
  },
  {
    name: "Instance E",
    gpu: "Sample",
    storage: "1.5 TB SSD",
    network: "20 Gbps",
    egress: "Unlimited",
    price_monthly: "$1,500",
    price_hourly: "$2.00",
  },
  {
    name: "Instance F",
    gpu: "Sample",
    storage: "256 GB SSD",
    network: "1 Gbps",
    egress: "1 TB",
    price_monthly: "$600",
    price_hourly: "$0.80",
  },
];
